### ISSUE TITLE
Need To Update and design README.md

### ISSUE THREAD

**Issue by saikatsardar01** [saikatsardar01/memetonic#1]
We are creating a meme sharing and viewing community. 
For the backend we gonna use :- TeraBox . { Users will upload their meme in Terabox and share us the link }
Then after a review process it will be added to the main page.
**FEATURES**
- Users can give like and reaction to the post.
- Post will be in a form of card.
- Users have to login before liking it.
- Admin dashboard.

Please mention this in the README.md file nicely.

No pull request will be accepted directly before assigning.

**Comment by Shivansh-22866** [comment]
I am ready to work on this, may I be assigned this issue to start working on it?

**Comment by Shivansh-22866** [comment]
I have made a basic readme file for the skeletal paragraphs, just check if it looks good
![Screenshot_20241006_232910](https://github.com/user-attachments/assets/0be0864e-a478-4f60-a356-de3f4010cdcf)
![Screenshot_20241006_232922](https://github.com/user-attachments/assets/3afba1d9-78e4-44c1-befa-44156acda175)
![Screenshot_20241006_232930](https://github.com/user-attachments/assets/1fe16c16-e157-4a5e-8350-7bb105cc9dc4)

**Comment by saikatsardar01** [comment]
Good remove contact section. And give a pull request

**Comment by Shivansh-22866** [comment]
Understood, other than that, is there any change that you would like to advice, after that, I can send a PR

**Comment by saikatsardar01** [comment]
No it it looking nice. Very soon I am going to raise different issues, so stay tuned to contribute on those also.

**Comment by Shivansh-22866** [comment]
I'll be sending you a PR very soon, keep a watch
